name: Deploy NodeJS application to AWS EC2 
on: 
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: root
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /home/ubuntu/GitHub-Actions-practice
          git pull
          docker compose update -d --build
          

    - name: Install dependencies
      run: npm install

    - name: Run application
      run: npm start